### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by sayakpaul** [MenghaoGuo/Awesome-Vision-Attentions#1]
Congratulations on publishing such a comprehensive paper. 

Would be nice to implement some of the methods mentioned therein and package that as a library with a focus on readability.

**Comment by MenghaoGuo** [comment]
Great suggestion !
I will implement some of the methods to make this paper easy to read and understand.

Thanks

**Comment by sayakpaul** [comment]
I am happy to cooperate too :)

**Comment by MenghaoGuo** [comment]
Thanks ! PR is welcome !
