### ISSUE TITLE
The top date is wrong I guess?

### ISSUE THREAD

**Issue by yassineAlouini** [MenghaoGuo/Awesome-Vision-Attentions#3]
It seem that the top date comes from a pre-filled template and is set to:

JOURNAL OF LATEX CLASS FILES, VOL. 14, NO. 8, AUGUST 2015 1

I guess it is wrong given how recent the paper is.

**Comment by MenghaoGuo** [comment]
Yeah, you are right. 

Thanks for your suggestion, i will fix it in the next version.
