### ISSUE TITLE
Consideration of "Local Importance-based Pooling" (LIP)  as an attention method

### ISSUE THREAD

**Issue by sebgao** [MenghaoGuo/Awesome-Vision-Attentions#6]
Hi Menghao,

Thanks for your great and helpful work. I regard our proposed LIP [1] also as a local attention method designed for the spatial downsampling procedure, whose weights are produced by a lightweight sub-network. Though being designed for spatial downsizing, it still falls in the regime of attention approaches. Could you please consider LIP also as an attention method *especially* for the pooling procedure?

By the way, the work TAM [2] done by our group is accepted by ICCV 2021. Please consider updating the venue of this paper.

[1] LIP: Local Importance-Based Pooling. ICCV 2019.
[2] TAM: Temporal Adaptive Module for Video Recognition. ICCV 2021.

**Comment by MenghaoGuo** [comment]
Hi, 

Thanks for your great work and kind suggestion for perfecting this paper. I will read the mentioned papers and consider your suggestions.

Best, 
Menghao
