### ISSUE TITLE
DIANet-AAAI2020 (Channel attention)

### ISSUE THREAD

**Issue by dedekinds** [MenghaoGuo/Awesome-Vision-Attentions#9]
Hi, nice work! Could you consider adding our paper "DIANet: Dense-and-Implicit Attention Network" ? [[paper]](https://ojs.aaai.org//index.php/AAAI/article/view/5842) [[code]](https://github.com/gbup-group/DIANet).

**Comment by MenghaoGuo** [comment]
Hi @dedekinds 

Thank you for your suggestion, we will consider adding it to the paper and this repo.
